import requests
import uuid

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    'Accept': 'application/json',
    'Origin': 'https://pluto.tv',
    'Referer': 'https://pluto.tv/'
}

EPG_URL = "https://sulthanpamenan.github.io/pluto-playlist/epg.xml"

def get_session():
    device_id = str(uuid.uuid4())
    session_id = str(uuid.uuid4())
    client_id = str(uuid.uuid4())
    
    boot_url = (
        f"https://boot.pluto.tv/v4/start"
        f"?appName=web&appVersion=9.22.0&clientDeviceType=0&clientID={client_id}"
        f"&deviceId={device_id}&deviceMake=chrome&deviceModel=web&deviceType=web"
        f"&marketingRegion=US&sessionID={session_id}"
    )
    
    token, channels = "", []
    try:
        res = requests.get(boot_url, headers=headers, timeout=15)
        if res.status_code == 200:
            d = res.json()
            token = d.get('sessionToken', '')
            channels = d.get('channels', [])
            print(f"[✓] Berhasil mengambil token dan {len(channels)} Live Channel.")
    except Exception as e:
        print(f"[!] Boot error: {e}")

    if not channels:
        try:
            res_v2 = requests.get("https://api.pluto.tv/v2/channels", headers=headers, timeout=15)
            if res_v2.status_code == 200:
                channels = res_v2.json()
        except Exception as e:
            print(f"[!] Fallback channels error: {e}")

    return token, device_id, session_id, client_id, channels

def build_m3u():
    token, device_id, session_id, client_id, channels = get_session()
    
    m3u_lines = [
        f'#EXTM3U url-tvg="{EPG_URL}"',
        "<!-- PLAYLIST AUTOGENERATED BY SULTHAN PAMENAN -->\n"
    ]

    for ch in channels:
        ch_id = ch.get('id') or ch.get('_id')
        if not ch_id:
            continue

        name = ch.get('name', 'Pluto Channel')
        logo = ch.get('logo', '')
        if isinstance(ch.get('colorLogoPNG'), dict):
            logo = ch.get('colorLogoPNG', {}).get('path', '')

        group = ch.get('category', 'Pluto TV')

        # Structure stream URL Live TV resmi Pluto TV yang kompatibel dengan HLS Player
        stream_link = (
            f"https://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/v2/stitch/hls/channel/{ch_id}/master.m3u8"
            f"?advertisingId=&appName=web&appVersion=9.22.0"
            f"&clientDeviceType=0&clientID={client_id}&clientModelNumber=1.0.0"
            f"&deviceDNT=false&deviceId={device_id}&deviceMake=chrome&deviceModel=web&deviceType=web"
            f"&sessionID={session_id}&sid={session_id}"
        )

        m3u_lines.append(f'#EXTINF:-1 tvg-id="{ch_id}" tvg-name="{name}" tvg-logo="{logo}" group-title="{group}",{name}')
        m3u_lines.append(stream_link)

    playlist_content = "\n".join(m3u_lines)
    
    with open("playlist.txt", "w", encoding="utf-8") as f:
        f.write(playlist_content)

    with open("playlist.m3u", "w", encoding="utf-8") as f:
        f.write(playlist_content)

    print(f"[SUCCESS] Berhasil memperbarui playlist dengan {len(channels)} Live Channel.")

if __name__ == "__main__":
    build_m3u()
