import requests
import uuid

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    'Accept': 'application/json',
    'Origin': 'https://pluto.tv',
    'Referer': 'https://pluto.tv/'
}

def build_vod_m3u():
    print("[*] Mengambil session JWT token untuk VOD...")
    device_id = str(uuid.uuid4())
    session_id = str(uuid.uuid4())
    client_id = str(uuid.uuid4())

    boot_url = (
        f"https://boot.pluto.tv/v4/start"
        f"?appName=web&appVersion=9.22.0-ba99318afe50de3c8a02021f4c92fd52f2c47a00"
        f"&clientDeviceType=0&clientID={client_id}&clientModelNumber=1.0.0"
        f"&deviceId={device_id}&deviceMake=chrome&deviceModel=web&deviceType=web"
        f"&deviceVersion=143.0.0&marketingRegion=US&serverSideAds=false&sessionID={session_id}"
    )

    token = ""
    try:
        res = requests.get(boot_url, headers=headers, timeout=15)
        if res.status_code == 200:
            token = res.json().get('sessionToken', '')
            print(f"[✓] Berhasil mendapatkan JWT token VOD: {token[:20]}...")
    except Exception as e:
        print(f"[!] Boot VOD Error: {e}")

    url = f"https://api.pluto.tv/v3/vod/categories?masterJWTPassthrough=true"
    if token:
        url += f"&jwt={token}"

    m3u_lines = [
        "#EXTM3U",
        "<!-- PLUTO VOD DIRECT PLAYLIST GENERATED BY SULTHAN PAMENAN -->\n"
    ]

    item_count = 0
    try:
        res = requests.get(url, headers=headers, timeout=20)
        if res.status_code == 200:
            categories = res.json().get('categories', [])
            for cat in categories:
                cat_name = cat.get('name', 'Pluto VOD')
                for item in cat.get('items', []):
                    item_id = item.get('_id')
                    name = item.get('name', 'VOD Item')
                    covers = item.get('covers', [])
                    logo = covers[0].get('url', '') if covers else ''

                    stream_link = (
                        f"https://cfd-v4-service-vod-stitcher-use1-1.prd.pluto.tv/v2/stitch/hls/episode/{item_id}/master.m3u8"
                        f"?advertisingId=&appName=web&appVersion=9.22.0-ba99318afe50de3c8a02021f4c92fd52f2c47a00"
                        f"&app_name=web&clientDeviceType=0&clientID={client_id}&clientModelNumber=1.0.0"
                        f"&country=US&deviceDNT=false&deviceId={device_id}&deviceLat=47.3000&deviceLon=-122.3700"
                        f"&deviceMake=chrome&deviceModel=web&deviceType=web&deviceVersion=143.0.0"
                        f"&marketingRegion=US&serverSideAds=false&sessionID={session_id}&sid={session_id}"
                        f"&userId=&jwt={token}&masterJWTPassthrough=true&includeExtendedEvents=true"
                    )

                    m3u_lines.append(f'#EXTINF:-1 tvg-id="vod_{item_id}" tvg-name="{name}" tvg-logo="{logo}" group-title="VOD - {cat_name}",{name}')
                    m3u_lines.append(stream_link)
                    item_count += 1
    except Exception as e:
        print(f"[!] Error VOD Fetch: {e}")

    content = "\n".join(m3u_lines)

    with open("vod_playlist.m3u", "w", encoding="utf-8") as f:
        f.write(content)

    with open("vod_playlist.txt", "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[SUCCESS] Berhasil memperbarui `vod_playlist.m3u` dengan {item_count} item VOD.")

if __name__ == "__main__":
    build_vod_m3u()
