import requests
import uuid

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    'Accept': 'application/json',
    'Origin': 'https://pluto.tv',
    'Referer': 'https://pluto.tv/'
}

# Tautkan URL EPG XMLTV milikmu di sini
EPG_URL = "https://sulthanpamenan.github.io/pluto-playlist/epg.xml"

def get_pluto_session():
    """Mengambil session token resmi dari endpoint boot Pluto TV"""
    device_id = str(uuid.uuid4())
    session_id = str(uuid.uuid4())
    client_id = str(uuid.uuid4())
    
    boot_url = (
        f"https://boot.pluto.tv/v4/start"
        f"?appName=web&appVersion=9.22.0-ba99318afe50de3c8a02021f4c92fd52f2c47a00"
        f"&clientDeviceType=0&clientID={client_id}&clientModelNumber=1.0.0"
        f"&deviceId={device_id}&deviceMake=chrome&deviceModel=web&deviceType=web"
        f"&deviceVersion=143.0.0&marketingRegion=US&serverSideAds=false&sessionID={session_id}"
    )
    
    token = ""
    channels = []
    categories = []
    
    try:
        res = requests.get(boot_url, headers=headers, timeout=15)
        if res.status_code == 200:
            data = res.json()
            token = data.get('sessionToken', '')
            channels = data.get('channels', [])
            categories = data.get('categories', [])
            print(f"[INFO] Token berhasil diambil: {token[:20]}...")
    except Exception as e:
        print(f"[ERROR] Boot fetch error: {e}")

    # Fallback jika channels kosong
    if not channels:
        try:
            res_v2 = requests.get("https://api.pluto.tv/v2/channels", headers=headers, timeout=15)
            if res_v2.status_code == 200:
                channels = res_v2.json()
        except Exception as e:
            print(f"[ERROR] Channels v2 fetch error: {e}")

    return token, device_id, session_id, client_id, channels, categories

def fetch_vod_items(token):
    """Mengambil konten VOD (On-Demand) Pluto TV"""
    vod_channels = []
    try:
        url = f"https://api.pluto.tv/v3/vod/categories?jwt={token}&masterJWTPassthrough=true"
        res = requests.get(url, headers=headers, timeout=15)
        if res.status_code == 200:
            data = res.json()
            for cat in data.get('categories', []):
                cat_name = cat.get('name', 'Pluto VOD')
                for item in cat.get('items', []):
                    vod_channels.append({
                        'id': f"vod_{item.get('_id')}",
                        'name': item.get('name', 'VOD Item'),
                        'logo': item.get('covers', [{}])[0].get('url', '') if item.get('covers') else '',
                        'category': f"VOD - {cat_name}",
                        'stitch_id': item.get('_id')
                    })
    except Exception as e:
        print(f"[!] Gagal mengambil VOD: {e}")
    return vod_channels

def build_m3u():
    token, device_id, session_id, client_id, channels, categories = get_pluto_session()
    
    m3u_lines = [
        f'#EXTM3U url-tvg="{EPG_URL}"\n',
        "<!-- PLAYLIST GENERATED BY SULTHAN PAMENAN -->"
    ]
        
    # 1. Memproses Channel Live TV
    for ch in channels:
        ch_id = ch.get('id') or ch.get('_id')
        if not ch_id:
            continue

        name = ch.get('name', 'Pluto Channel')
        
        logo = ''
        if isinstance(ch.get('colorLogoPNG'), dict):
            logo = ch.get('colorLogoPNG', {}).get('path', '')
        elif isinstance(ch.get('logo'), str):
            logo = ch.get('logo')

        group = ch.get('category', 'Pluto TV')

        stream_link = (
            f"https://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/v2/stitch/hls/channel/{ch_id}/master.m3u8"
            f"?advertisingId=&appName=web&appVersion=9.22.0-ba99318afe50de3c8a02021f4c92fd52f2c47a00"
            f"&app_name=web&clientDeviceType=0&clientID={client_id}&clientModelNumber=1.0.0"
            f"&country=US&deviceDNT=false&deviceId={device_id}&deviceLat=47.3000&deviceLon=-122.3700"
            f"&deviceMake=chrome&deviceModel=web&deviceType=web&deviceVersion=143.0.0"
            f"&marketingRegion=US&serverSideAds=false&sessionID={session_id}&sid={session_id}"
            f"&userId=&jwt={token}&masterJWTPassthrough=true&includeExtendedEvents=true"
        )

        m3u_lines.append(f'#EXTINF:-1 tvg-id="{ch_id}" tvg-name="{name}" tvg-logo="{logo}" group-title="{group}",{name}')
        m3u_lines.append(stream_link)

    # 2. Memproses Content VOD
    vod_list = fetch_vod_items(token)
    for vod in vod_list:
        v_id = vod['id']
        v_name = vod['name']
        v_logo = vod['logo']
        v_group = vod['category']
        s_id = vod['stitch_id']

        vod_link = (
            f"https://cfd-v4-service-vod-stitcher-use1-1.prd.pluto.tv/v2/stitch/hls/episode/{s_id}/master.m3u8"
            f"?appName=web&clientID={client_id}&deviceId={device_id}&sessionID={session_id}&jwt={token}"
        )

        m3u_lines.append(f'#EXTINF:-1 tvg-id="{v_id}" tvg-name="{v_name}" tvg-logo="{v_logo}" group-title="{v_group}",{v_name}')
        m3u_lines.append(vod_link)

    playlist_content = "\n".join(m3u_lines)
    
    with open("playlist.txt", "w", encoding="utf-8") as f:
        f.write(playlist_content)

    with open("playlist.m3u", "w", encoding="utf-8") as f:
        f.write(playlist_content)
        
    print(f"[SUCCESS] Berhasil memperbarui playlist! (Total Live: {len(channels)}, VOD: {len(vod_list)})")

if __name__ == "__main__":
    build_m3u()
