import requests
import uuid

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    'Accept': 'application/json',
    'Origin': 'https://pluto.tv',
    'Referer': 'https://pluto.tv/'
}

PROXIES = {
    'http': 'http://154.21.137.234:3128',
    'https': 'http://154.21.137.234:3128'
}

MIRROR_VOD_URL = "https://raw.githubusercontent.com/matthuisman/i.mjh.nz/master/PlutoTV/vod.m3u"

def build_vod_m3u():
    print("[*] Memulai pemrosesan VOD On-Demand...")
    device_id = str(uuid.uuid4())
    session_id = str(uuid.uuid4())
    client_id = str(uuid.uuid4())

    boot_url = f"https://boot.pluto.tv/v4/start?appName=web&appVersion=9.22.0&clientID={client_id}&deviceId={device_id}&sessionID={session_id}"
    token = ""
    
    try:
        res_b = requests.get(boot_url, headers=headers, proxies=PROXIES, timeout=15)
        if res_b.status_code == 200:
            token = res_b.json().get('sessionToken', '')
    except Exception:
        pass

    url = "https://api.pluto.tv/v3/vod/categories?masterJWTPassthrough=true"
    if token:
        url += f"&jwt={token}"

    m3u_lines = [
        "<!-- PLUTO VOD AUTOGENERATED BY SULTHAN PAMENAN -->\n",
        "#EXTM3U\n"
    ]
    item_count = 0
    
    # 1. Coba tarik dari API Pluto TV via Proxy
    try:
        res = requests.get(url, headers=headers, proxies=PROXIES, timeout=20)
        if res.status_code == 200:
            categories = res.json().get('categories', [])
            for cat in categories:
                cat_name = cat.get('name', 'Pluto VOD')
                for item in cat.get('items', []):
                    item_id = item.get('_id')
                    name = item.get('name', 'VOD Item')
                    covers = item.get('covers', [])
                    logo = covers[0].get('url', '') if covers else ''

                    stream_link = (
                        f"https://cfd-v4-service-vod-stitcher-use1-1.prd.pluto.tv/v2/stitch/hls/episode/{item_id}/master.m3u8"
                        f"?appName=web&appVersion=9.22.0-ba99318afe50de3c8a02021f4c92fd52f2c47a00"
                        f"&clientID={client_id}&deviceId={device_id}&sessionID={session_id}"
                    )
                    if token:
                        stream_link += f"&jwt={token}"

                    m3u_lines.append(f'#EXTINF:-1 tvg-id="vod_{item_id}" tvg-name="{name}" tvg-logo="{logo}" group-title="VOD - {cat_name}",{name}')
                    m3u_lines.append(stream_link)
                    item_count += 1
            print(f"[✓] Berhasil menarik {item_count} VOD dari API.")
    except Exception as e:
        print(f"[!] Error VOD Direct API: {e}")

    # 2. Jika API gagal/kosong akibat geo-block, gunakan mirror publik otomatis
    if item_count == 0:
        print("[*] Mengunduh VOD dari mirror publik...")
        try:
            res_m3u = requests.get(MIRROR_VOD_URL, timeout=30)
            if res_m3u.status_code == 200:
                content = "<!-- PLUTO VOD AUTOGENERATED BY SULTHAN PAMENAN -->\n\n" + res_m3u.text
                with open("vod_playlist.m3u", "w", encoding="utf-8") as f:
                    f.write(content)
                with open("vod_playlist.txt", "w", encoding="utf-8") as f:
                    f.write(content)
                print("[SUCCESS] vod_playlist.m3u berhasil diperbarui via mirror!")
                return
        except Exception as e:
            print(f"[!] Error VOD Mirror: {e}")
            return

    content = "\n".join(m3u_lines)
    with open("vod_playlist.m3u", "w", encoding="utf-8") as f:
        f.write(content)
    with open("vod_playlist.txt", "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[SUCCESS] vod_playlist.m3u berhasil diperbarui ({item_count} item).")

if __name__ == "__main__":
    build_vod_m3u()
