name: Update Pluto Playlist & EPG

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Generate Live TV Playlist
        run: python generate.py

      - name: Generate EPG XML
        run: python generate_epg.py

      - name: Generate Separate VOD Playlist
        run: python generate_vod.py

      - name: Commit and Push Updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update Live TV, EPG, & VOD [skip ci]" && git push)
